# Iterative Study Design {#iterative-design}

At this early stage of the project, the goal is to put together a solid research plan and get your whole team on the same page. This is an iterative process, meaning that you'll start organizing your thinking on study aims and design and do some initial data exploration. Then you'll check-in with your mentors and collaborators and revise your study design and methods, and check back in with your team to see if further changes are needed. While you do this work, you can plan ahead and start assembling the information you'll need to eventually write a manuscript for peer review.

## Workflow

Here are my suggestions for how to organize your work at the study design stage. See below for more detailed descriptiosn of each of the tools mentioned here.

### Outline your background, aims, and methods


Using a High Level Outline (described below), .

### Set up your project directory and assemble data

If you're looking for a system, see the **Setting up Your Project Directory** section below for my suggestions.

### Explore your data

Using a Data Memo (described below)

### Ask for feedback

Different mentors and research groups have different approaches to providing feedback. Ask your mentor about their approach, how they like to provide
Ideally you have a network of formal mentors ready to provide feedback, including your adviser and other members of your lab group.
Also: community partners

### Iterate

Revise your high level outline. Do more exploratory analyses. Talk to your colleagues. Read similar papers in the literature, paying attention to their framing, methods, and findings. Are there methods you can adapt or build on? Papers you should cite? Hypotheses you can follow up on? Ask for more feedback. Finally, once you, your mentors, and your collaborators agree that you have a solid plan, move on to the Primary Research stage.

## Tools

At this early stage of the project, I suggest using the following tools to organize your thinking and get feedback from colleagues: a project log, a high level outline, data memos, a reference manager, and a style guide.

### Project Log

You need a system to organize project-specific notes and tasks, particularly when you're conducting multiple projects at the same time. There are several ways to do this, including a task management app, a Word doc, or on paper. I use a basic text document with [Markdown](https://www.markdownguide.org/getting-started/). I don't usually share this document, which I call the Project Log, a sort of digital lab book. I organize the Project Log into two section: *Meta* and the *Daily Log*.

The *Meta* section includes:

- Project Information, including full list of authors' full names, affiliations, and email. You'll need this when you fill out the forms to submit manuscripts to journals (and you can expect to have to submit to multiple journals). You can also keep a list of conferences where you presented your project at; sometimes journals ask for this information, too.
- Journal Information, including a list of journals you'd like to submit to, possibly in order of preference.
- Data, including each datasets name, short description of where it came frame, and any references. Colleagues might where you got a particular dataset from for their own projects, and journals may ask you to include this information in a data availabiltiy statement.
- Tasks, which is basically a to do list. Before I close out a work session, I write a short note here to remind myself where to pick up next time.

In the *Daily Log* section, you can take running notes on decision you're making throughout the project. You don't need to write down everything, focus on decision points that you might want to refer back to later. For example, you could take notes from a team meeting on which dataset you decided to use and where you downloaded it from, or which journal your team ended up submitting to first and why you chose it. 

### High Level Outline

This tool comes from [Luby and Southern (2023)](https://doi.org/10.1007/978-3-030-98175-4), *The Pathway to Publishing: A Guide to Quantitative Writing in the Health Sciences*, and is a helpful organizing document for both the writer and anyone reviewing the document. In this document, the writer briefly summarizes the study's context, the gap it addresses, and its objectives. The writer also concisely describes the study design, data, and methods, outlines tables and figures, and anticipates strengths, limitations, and prospective findings and conclusions.

As described by Luby and Southern: 

> "The role of the high level outline is to sketch out the major components of the manuscript  that will support the data analysis included in the framing document *[another writing tool suggested by Luby and Southern]*. This is an outline,that should be no longer than 1500 words (excluding the tables, figures and references). Full sentences are not necessary.

> "Keeping the document short helps the author focus on the key elements of the manuscript, and provides early high level input. Because a short document takes less time for authors to produce and less time for co-authors to review, it generates prompt feedback on key ideas, and so supports a faster path to publication. Using this approach  prevents authors investing weeks or months developing full draft manuscripts, that are off target with pages and pages of prose that need to be discarded."

I highly recommend reading [Luby and Southern (2023)](https://doi.org/10.1007/978-3-030-98175-4) to learn more about their approach to scientific writing and to see templates of the high level outline and other writing tools.

### Data Memos

A data memo is an RMarkdown (for R users) or Jupityr [confirm] (for Python users) file that describes something about your data. In the design stage, this is mainly for getting to know your datasets in a way you can share with your colleagues. For example, you could take a dataset on daily PM2.5 measurements across a monitoring network and write a RMarkdown with basic plots showing the distributions of the measurements and which monitors observed the highest average PM2.5 concentrations.

### Reference Manager

You're probably using one of these already. References managers like [Zotero](https://www.zotero.org/), [Mendeley](https://www.mendeley.com/), [EndNote](https://endnote.com/), and [PaperPile](https://paperpile.com/) (my favorite) help you organize your reading, take notes, and write manuscripts with in-text citations. The UC Berkeley Library has more information on reference managers [here](https://guides.lib.berkeley.edu/publichealth/citations).

### Style Guide

A style guide is a system for writing consistent and readable code, including syntax, layout, and naming conventions for functions and objects. Again, the goal is to reduce the number of logistical decisions you need to make so you can focus on your research. You don't need to invent your own system, but you should feel free to iterate on the existing ones. I use [The tidyverse style guide](https://style.tidyverse.org/index.html) to style my R code, and there are other options out there, including the [Google R Style Guide](https://google.github.io/styleguide/Rguide.html). Other languages have their own style guides, such as the [PEP 8 Style Guide for Python](https://peps.python.org/pep-0008/).

## Setting up Your Project Directory {#project-directory}

[Brief Intro]

### Naming projects

Each project gets it's own directory (aka folder), and each of those directories needs a name. I try to keep things simple and consistent, so I use this basic convention for naming projects: Setting-Exposure-Outcome. For example, a project where the setting is California, the exposure is wildfire smoke, and the outcome is preterm birth, I would name the directory: `cal-wildfiresmoke-ptb`.

### Naming files

I like to keep file names short and simple. If you follow the above strategy, then information about the project is already conveyed in the directory structure itself. Also, there's no need to write specific names for documents every project has, like the manuscript or supplementary materials. I keep these filenames simple, e.g., `manuscript01` or `supplementary01`. With each iteration, you can simply go to the next draft number. I.e., the second draft would be `manuscript02`. When you ask co-authors for feedback, they can add their initials at the end of the filename (e.g., `manuscript02-abc-xyz`). When you're ready to you incorporate co-author feedback, you can again simply move on to the next number (`manuscript03`).

### Organizing your directory

[Figure. Example Project Directory]

### Resources

You can download a full template for my research project structure [here](), including templates for the Concept Note and Project Log.