# Submission and Peer Review {#submission}

Your manuscript and all other materials are finalized and now you're ready to submit. There are a few steps you should take before you fill out the journal's webform and upload your files.

## Before you submit

### Double-check the author guide

If your submission isn't properly structured and formatted, a journal editor could reject it without reading the material, sending it back to you to make the required changes. So make sure your manuscript is properly formatted, with the correct organization, headings, citation style, etc. This should all be outlined in the journal's guide for authors (and sometimes also in a checklist), so make sure to read that carefully.

### Write a cover letter

Cover letters are an opportunity to describe to the journal's editors what your manuscript adds to the literature and a why it's good fit for their journal. [expand]

Some journals require cover letters, some do not. 
There are a wide variety of cover letters, so make sure to read the author guidelines closely to see what the journal asks for.
Among journals that do require cover letters, sometimes you need to make specific declarations regarding, for example, authors' contributions and that the study isn't under consideration elsewhere. Sometimes they simply want you to describe why they should publish your paper.

In terms of formatting, depends on how the journal wants you to send the cover letter. When journals asks me to upload cover letters, I'll typically use a letter head so it comes across as professionmal correspondence (which it is).
Sometimes the cover letter is included as another text field in the form to submit a paper. In those cases, I drop the formality and simply respond to what they need.
In all scenarios, I think it's good to be concise!

[add examples-one formal, one informal]
[ten simple rules for this? other resources?]

### Assemble your materials


- Cover letter (if required)
- Your manuscript, properly formatted and styled.
- Tables and figures, either included in the manuscript or uploaded separately, depending on the journal's requirements.
- Supplementary information, again, properly formatted. Check to 
- Meta data for the study, including information on your co-authors (their full names, affiliatins, email addresses, and ORCIDs), funding (grants to mention with relevant numbers and initials for the co-authors attached to them),
- Notes on any relevant conflicts of interest among the authorship team, or confirmation from each co-author that they have none to report
- Suggested peer reviewers who would be well-qualified to provide a review but who are not collaborators

If you've followed the steps in this Handbook, you should already have most of the information the journal will ask for in your Project Log.

## Article preprints

[what they are, advantages/things to consider, what to expect when submitting (minimal screening)]

## Submitting to a peer reviewed journal journal


Typically, the system will generate a PDF proof with all of your materials. Give it one final look, verify that everything is there that you uploaded the correct drafts, properly formatted. If everything looks good--hit submit.

Congratulations!

Send an email update to your co-authors, attach the auto-generated PDF proof, and let them know you'll keep them in the loop about the journal's decision.

## How peer review works

[editors review articles, make a decision as to whether to send to peer reviewers]
[typically several peer reviewers...]
[be prepared for this to be a slow process...]

### Types of editorial decisions

* **Desk rejection.** The editors made a decision to reject your paper without sending it on to peer reviewers. Sorry. This is common, don't sweat it, just move on and submit to the next journal on your list!
* **Rejection after peer review.** The editor thought your paper was fit to send to peer reviewers, but after receiving those reviews, decided to reject the paper. Sorry, again, not uncommon at all. Ideally you'll be able to see the comments from the peer reviewers, which you can bring to your team and decide whether and how to address them before re-submitting or submitting to a different journal.
* **Revise and re-submit.** [expand] Below I discuss strategies to address reviewer comments.
* **Accepted.** Congratulations! Typically, you'll need to go through several rounds of revisions before you reach this stage. It is very rare for papers to be accepted without revisions, but it does happen.

## Addressing reviewer comments

Every comment needs to be addressed. Take a professional and respectful tone, even if the comments themselves are not. It's common, but not necessary, to thank reviewers for their suggestions.

As you respond to comments, make it easy for the editors and peer reviewers by saying where you made changes and what you changed text to.You don't have to agree with everything the the reviewer suggested. [expand]

[give your co-authors a chance to respond and give them a deadline; if they don't respond by then (and you're not waiting on critical input), you can move ons]

[who to talk to about reviewer comments]

[add link to 'Ten Simple Rules' for peer review article]