# Publication and Outreach {#publication}

Congratulations! You're about to be a published author. Make sure you share the good news with your co-authorship team. 

That said, your job's not over yet. Accepted papers don't get published immediately and a few steps remain.

## Getting from accepted to published

After a journal accepts your paper, you'll need to do a few more tasks to get to a publication-ready article:

- Review galley proofs [describe]. Respond to any questions from journal editorial staff. Verify all of the authors' names are spelled correctly and that everyone is matched with the right institutional affiliation. Finally, give your manuscript one last proofread—-once typos are published, they're permanent!

## Open access publishing

As scientists, our primary form of communication with other scientists is through publishing papers in peer reviewed journals. Each journal requires staff and resources to do their work, and this means that, in one form or another, they need funding. Historically, journals generated revenue by charging readers for access to the studies they publish, usually by offering subscriptions to libraries or research institutions. This creates a problem for people who aren't affiliated with a research institution. You'd have to pay for your own subscription to read primary research articles. As of June 2024, it costs $30/month to subscribe to the *Nature* family of journals, pricier than a monthly subscription to the New York Times. And if you want to read a paper from another journal, you'd need to pay for another subscription. The costs of accessing scientific knowledge can add up quickly. This is particularly irksome when you consider that much of the research is publicly funded. 

Over the past decade, there has been a growing movement to ensure that scientific articles are open access, which means that they are free to read for anyone, no subscription required. The policies and practices around open access publishing are rapidly evolving. Below, I discuss a few of the options I've used for my work. See this [explainer](https://www.lib.berkeley.edu/research/scholarly-communication/open-access?section=about-open-access){target="_blank"} from the UC Berkeley library for more.

### Paying for open access

Many journals now allow authors who want their work to be open access to pay an article processing charge (APC) to offset any lost revenue from subscribers. Journal APCs range widely. For example, the journal *[Environmental Epidemiology](https://journals.lww.com/environepidem/Pages/openaccess.aspx){target="_blank"}*, supported by the non-profit International Society for Environmental Epidemiology, has an APC of $1,260 USD. On the other end of the spectrum, *[Nature Climate Change](https://www.nature.com/nclimate/submission-guidelines/publishing-options)* has an APC of \$12,290 USD.

For-profit academic publishers such as Springer-Nature and Elsevier operate with high profit margins. For example, *The Guardian* [reports](https://www.theguardian.com/science/2017/jun/27/profitable-business-scientific-publishing-bad-for-science){target="_blank"} that Elsevier's scientific publishing activities generated \$926 million USD in profit in 2010 alone.

If you're interested in publishing your article in open access, make sure to talk to your PI or adviser early, around the time you're choosing which journals to submit to. You should discuss what kind of funding, if any, is available to support open access and alternatives that don't require an APC. 

### Alternatives to paying for open access

The costs of open access can be prohibitively expensive under the best circumstances, and some  popular for-profit publishing firms have exorbitant APCs. High APCs can be a drain on already constrained scientific funding, particularly for researchers from under-resourced institutions, and there are genuine ethical concerns to using research funding to support for-profit publishers. It's okay not to pay a journal for open access, though this will mean that readers accessing your article through the journal will encounter a paywall.

Fortunately, if you  don't have funding or if you simply don't want to use your funding to pay an high fee, there are other ways to make our study freely available to the public:

- **Preprint Servers** - Many journals will allow you to post your accepted manuscript to a preprint server, such as [arXiv](https://arxiv.org/){target="_blank"}, [MedRxiv](https://www.medrxiv.org/){target="_blank"}, or [EarthArXiv](https://eartharxiv.org/){target="_blank"}. The accepted manuscript is the final draft of your submission to a journal after peer review has been done, but before it has been professionally formatted (so it's usually a Word document). If you've already uploaded an earlier draft of your manuscript to a preprint server, you can update it with the final accepted manuscript.
- **Institutional Repositories** - Many universities maintain their own repositories where you can upload your work and receive a permanent link, which is valuable for citing and sharing your work. Researchers affiliated with the University of Californi can upload accepted manuscripts to [eScholarship](https://escholarship.org/){target="_blank"}. Depending on the journal's policies, you may be required to wait a few months (an "embargo period") before you upload your manuscript.
- **PubMed Central** - If one of the co-authors on the study was supported by a grant from a federal agency or certain foundations, you may be required to post an accepted manuscript on [PubMed Central (PMC)](https://www.ncbi.nlm.nih.gov/pmc/about/public-access/){target="_blank"}. According to NIH, "PMC is the full-text repository for papers that fall under the public and open access policies of a number of research funding organizations that support biomedical and life science research."
- **Personal Websites** - You're often allowed to upload a PDF of your manuscript to your own personal website without restriction.
- **Open Access Journals** - Some journals, such as the [NIEHS](https://www.niehs.nih.gov/){target="_blank"}-funded *[Environmental Health Perspectives](https://ehp.niehs.nih.gov/){target="_blank"}*, are open access by default and don't charge an APC.

Before you upload your manuscript, make sure to check the journal's policies to see what kind of sharing is allowed.

## Sharing your paper

### Get organized

If you'd like to seek news coverage for your article, after your paper has been published you ask the journal to set an embargo date. 

An embargo date is a set date when the journal releases the article. Once you have the date, you can share it with your institution's press office if they're issuing a press release. You can also share the embargo date and the embargoed accepted manuscript directly with journalists who may be interested in covering the study. The idea is that the scientific paper, press release, and news articles will all be released at the same time to help the study make a bigger splash.


Things to assemble:

- Photos or other visual aids. Communications staff and journalists often ask for this. You can be a published author *and* photographer!
- Key points that you'd like to make sure you convey to all of the media and communications professionals you work with. If your paper is newsworthy, you're probably going to get similar questions from multiple people. Make sure to provide a consistent message.

Coordinate with journal outreach staff. Many journals promote their new publications on social media, so you should share your handles and any key points you'd like them to highlight.


### Working with communications staff at your institution

Your institution may have an office devoted to sharing new research with the public. Communications staff can share your work on the institution's social media, issue press releases that go out to news outlets, and help you prepare for media interviews. Check with the communications staff at your university for specifics about how you can share your newly accepted articles with them and the kind of support they can offer.

### Working with journalists

If journalists reach out to you requesting an interview, it's important to take the time to prepare. Read your paper again to refresh your memory. Make a list of key points you want to convey. If a finding was unexpected or surprised you, be prepared to talk about it. And of course, reach out to your mentors and ask their advice. 

You can also to take a basic media training course. The [Science Communication Network](https://sciencecommunicationnetwork.org/){target="_blank"} provides resources for scientists and health professionals to improve public outreach skills and connects journalists with environmental health experts.

If you're affiliated with a research institution, you might have access to a media and communications office, with professional staff who can help you in your science outreach. At UC Berkeley, students, staff, and faculty can access a [Media Training for Academics](https://news.berkeley.edu/media-training){target="_blank"} course offered by the Office of Communications and Public Affairs and the Greater Good Science Center.

## Reaching diverse audiences

It takes extra effort to reach diverse audiences with your work. Below I share some strategies for practicing linguistic inclusion.

*Note: This section is incomplete.*

### Linguistic inclusion

Colleagues and I discussed strategies for practicing linguistic inclusion in a [2023 paper](https://doi.org/10.1289/EHP12306){target="_blank"} published in *Environmental Health Perspectives*.

### Public writing

You can pitch public-facing articles on your scientific work to outlets including *The Conversation* and *Environmental Health News*.

If you have a timely policy-relevant study, you can also consider pitching an op-ed to newspapers. 

### Policy briefs

Policy stakeholders

### Social media

Not my forté, but social media is an important way to reach some audiences. That said, social media is not the be-all end-all. Be mindful of who you do and do not reach through social media and the tradeoff between social media engagement and doing other forms of public outreach.